### ISSUE TITLE
Building paon

### ISSUE THREAD

**Issue by matta** [negrel/paon#8]
Hello, I stumbled across paon while searching for go TUI packages.

Looks interesting, but looks like it is not building currently? I'm set up with flakes, so it seems like my build environment should be similar to yours.

```
% git checkout HEAD %% make tests
go generate ./...
2024/06/15 14:22:37 Loading input failed: don't know how to mock method of type *ast.IndexExpr
widgets/gen.go:3: running "mockgen": exit status 1
make: *** [Makefile:5: tests] Error 1
```

```
% git checkout 'HEAD^' && make test
go generate ./...
go test -v -timeout 30s ./...
widgets/hbox/widget.go:6:2: no required module provides package github.com/negrel/paon/math; to add it:
	go get github.com/negrel/paon/math
```

% git checkout 'HEAD^^^^^' && make test                                              ~/scratch/paon
Previous HEAD position was cd0a428 add styles.Renderable
HEAD is now at b88b2a8 add some layout tests
go generate ./...
go test -v -timeout 30s ./...
# github.com/negrel/paon/widgets/span
widgets/span/widget.go:21:11: undefined: widgets.BaseWidget
widgets/span/widget.go:32:25: undefined: widgets.NewBaseWidget
widgets/span/widget.go:34:3: unknown field Widget in struct literal of type widgets.InheritStyle
# github.com/negrel/paon/widgets/hbox
widgets/hbox/widget.go:16:6: w.Node undefined (type *Widget has no field or method Node)
widgets/hbox/widget.go:25:4: unknown field Widget in struct literal of type widgets.InheritStyle
widgets/hbox/widget.go:35:10: undefined: widgets.StyledLayout
widgets/hbox/widget.go:42:27: undefined: widgets.NewStyledLayout
widgets/hbox/widget.go:43:11: undefined: widgets.NewBaseWidget
widgets/hbox/widget.go:49:19: w.Node undefined (type *Widget has no field or method Node)
widgets/hbox/widget.go:87:4: unknown field Widget in struct literal of type widgets.InheritStyle
# github.com/negrel/paon/widgets/vbox
widgets/vbox/widget.go:16:6: w.Node undefined (type *Widget has no field or method Node)
widgets/vbox/widget.go:25:4: unknown field Widget in struct literal of type widgets.InheritStyle
widgets/vbox/widget.go:32:10: undefined: widgets.StyledLayout
widgets/vbox/widget.go:38:27: undefined: widgets.NewStyledLayout
widgets/vbox/widget.go:39:11: undefined: widgets.NewBaseWidget
widgets/vbox/widget.go:45:19: w.Node undefined (type *Widget has no field or method Node)
widgets/vbox/widget.go:83:4: unknown field Widget in struct literal of type widgets.InheritStyle

**Comment by negrel** [comment]
Hi! Currently it's in a broken state and there is no release. I'm not actively working on this project for now...

Maybe https://github.com/charmbracelet/bubbletea will fit your needs.
